# .goreleaser.yml

version: 2
project_name: canary-gate
before:
  hooks:
    - go mod tidy
builds:
  - <<: &build
      binary: canary-gate
      main: ./cli/
      ldflags:
        - -s -w -X main.VERSION={{ .Version }}
      env:
        - CGO_ENABLED=0
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - <<: *build
    id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - <<: *build
    id: windows
    goos:
      - windows

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: linux_darwin
    ids:
      - linux
      - darwin
  - formats:
      - zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: windows
    ids: 
      - windows

checksum:
  name_template: 'checksums.txt'

homebrew_casks:
  - name: canary-gate
    homepage: "https://github.com/KongZ/canary-gate"
    description: "A Canary-Gate CLI tool for managing canary deployments."
    license: "Apache-2.0"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/canary-gate"]
          end
    repository:
      owner: "KongZ"
      name: "homebrew-tap"
      token: "{{ .Env.GITHUB_TOKEN }}"