apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/component: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: demo
      app.kubernetes.io/name: demo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: demo
        app.kubernetes.io/name: demo
    spec:
      automountServiceAccountToken: false
      containers:
        - name: demo
          image: ghcr.io/kongz/piggy-demo:1.0
          resources:
            limits:
              memory: "64Mi"
              cpu: "200m"
          ports:
           - containerPort: 8080