{{- if and .Values.crd.create (eq .Values.store.type "crd") -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must be in the format: <plural>.<group>
  name: canarygates.piggysec.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: piggysec.com
  # list of versions supported by this CRD
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                confirm-rollout:
                  type: string
                pre-rollout:
                  type: string
                rollout:
                  type: string
                confirm-traffic-increase:
                  type: string
                confirm-promotion:
                  type: string
                post-rollout:
                  type: string
                rollback:
                  type: string
                flagger:
                  type: object
                  # This allows the 'flagger' field to contain any valid JSON/YAML structure.
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    analysis:
                      type: object
                      properties:
                        webhooks:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              url:
                                type: string
                              timeout:
                                type: string
                              metadata:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: canarygates
    # singular name to be used as an alias on the CLI and for display
    singular: canarygate
    # kind is normally the PascalCased singular type. Your resource manifests use this.
    kind: CanaryGate
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cg
{{- end }}