{{- if and .Values.crd.create (eq .Values.store.type "crd") -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: canarygates.piggysec.com
spec:
  group: piggysec.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: # You should require the flagger field
              - flagger
              - target
              properties:
                confirm-rollout:
                  type: string
                pre-rollout:
                  type: string
                rollout:
                  type: string
                confirm-traffic-increase:
                  type: string
                confirm-promotion:
                  type: string
                post-rollout:
                  type: string
                rollback:
                  type: string
                target: 
                  type: object
                  required:
                  - namespace
                  - name
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string                   
                flagger:
                  description: Contains the raw spec for the Flagger Canary resource.
                  type: object
                  # This is the most important part. It corresponds to the
                  # 'runtime.RawExtension' type in your Go struct and allows
                  # any valid YAML/JSON structure inside.
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: canarygates
    singular: canarygate
    kind: CanaryGate
    shortNames:
    - cg
{{- end }}