apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canary-gate.fullname" . }}
  labels:
    {{- include "canary-gate.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "canary-gate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "canary-gate.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canary-gate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - vv
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort:  {{ .Values.metrics.port }}
              protocol: TCP
            - name: controller
              containerPort:  {{ .Values.controller.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: controller
          readinessProbe:
            httpGet:
              path: /readyz
              port: controller
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "10m" }}
              memory: {{ .Values.resources.requests.memory | default "32Mi" }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage | default "128Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "100m" }}
              memory: {{ .Values.resources.limits.memory | default "128Mi" }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeralStorage | default "256Mi" }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: CANARY_GATE_NAME
              value: {{ .Release.Name }}
            - name: CANARY_GATE_ENDPOINT
              value: {{ include "canary-gate.service.endpoint" . | quote }}
            - name: CANARY_GATE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CANARY_GATE_STORE
              value: {{ .Values.store.type | quote }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
