{{- if .Values.serviceAccount.create -}}
# Define a namespaced Role for CanaryGate CRD access
# This Role only grants permissions within the namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "canary-gate.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
# Bind the namespaced Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "canary-gate.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "canary-gate.fullname" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "canary-gate.serviceAccountName" . }}
---
# Define a ClusterRole for CanaryGate CRD access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "canary-gate.fullname" . }}
rules:
  - apiGroups: ["piggysec.com"]
    resources: ["canarygates"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["piggysec.com"]
    resources: ["canarygates/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [ "piggysec.com" ]
    resources: [ "canarygates/finalizers" ]
    verbs: [ "update" ]
---
# Define a ClusterRole for Flagger Canary CRD access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "canary-gate.fullname" . }}-flagger-writer
rules:
  - apiGroups: ["flagger.app"]
    resources: ["canaries"]
    verbs: [ "create", "get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Bind the ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "canary-gate.fullname" . }}-flagger-writer
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "canary-gate.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "canary-gate.fullname" . }}-flagger-writer
  apiGroup: rbac.authorization.k8s.io
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "canary-gate.fullname" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "canary-gate.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "canary-gate.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}