apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-gate.fullname" . }}
  labels:
    {{- include "canary-gate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "canary-gate.selectorLabels" . | nindent 4 }}
