name: Build and Test wihtout Docker

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Download modules
        run: |
          go mod download
          go install staticcheck@latest
          go install gosec@latest
      - name: Run test
        run: make build
      - name: Report coverage
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
      - name: Build image
        run: make docker